USER_INFO:
  user_name: '<INSERT USER NAME>'
  region: 'us-east-1'
  email: '<INSERT PREFERED EMAIL>'


CAMERA_TRAP:
  bucket_name: 'from-camera-trap-1'
  allow_delete: True
  root_dir: './data/images/species_validate/loxodonta_cyclotis'
  val_meta: './data/obs_and_meta/processed/probocidia_validation.csv'


IMG_EVENT_TBL:
  table_name: 'image_event'
  attr_def:
    - attributeName: "event_id"
      attributeType: "S"
  key_schema:
    - attributeName: "event_id"
      keyType: "HASH"
