apiVersion: v1
kind: Service
metadata:
  name: wildsight-edgecloud-service
spec:
  selector:
    app: wildsight-edgecloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
